# Generated by Django 3.0 on 2020-04-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variabletipo',
            name='Descripcion',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
    ]
