# Generated by Django 3.0 on 2020-04-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Score', '0002_variabletipo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablevalor',
            name='Puntaje',
            field=models.IntegerField(default=0),
        ),
    ]
