# Generated by Django 3.0 on 2020-04-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Score', '0003_variablevalor_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablevalor',
            name='Valor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='variablevalor',
            unique_together={('Nombre', 'Valor', 'Puntaje')},
        ),
    ]
