# Generated by Django 3.0 on 2020-04-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Score', '0004_auto_20200405_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Riesgo', models.CharField(max_length=200, null=True, unique=True)),
                ('Nombre', models.CharField(max_length=200, null=True, unique=True)),
                ('Descripcion', models.CharField(max_length=500, null=True)),
                ('PuntajeMinimo', models.IntegerField(default=0)),
                ('PuntajeMaximo', models.IntegerField(default=0)),
                ('Enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
